/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AethersignRouteImport } from './routes/aethersign'
import { Route as AetherinvoiceRouteImport } from './routes/aetherinvoice'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const AethersignRoute = AethersignRouteImport.update({
  id: '/aethersign',
  path: '/aethersign',
  getParentRoute: () => rootRouteImport,
} as any)
const AetherinvoiceRoute = AetherinvoiceRouteImport.update({
  id: '/aetherinvoice',
  path: '/aetherinvoice',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aetherinvoice': typeof AetherinvoiceRoute
  '/aethersign': typeof AethersignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aetherinvoice': typeof AetherinvoiceRoute
  '/aethersign': typeof AethersignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aetherinvoice': typeof AetherinvoiceRoute
  '/aethersign': typeof AethersignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/aetherinvoice' | '/aethersign'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/aetherinvoice' | '/aethersign'
  id: '__root__' | '/' | '/about' | '/aetherinvoice' | '/aethersign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AetherinvoiceRoute: typeof AetherinvoiceRoute
  AethersignRoute: typeof AethersignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aethersign': {
      id: '/aethersign'
      path: '/aethersign'
      fullPath: '/aethersign'
      preLoaderRoute: typeof AethersignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aetherinvoice': {
      id: '/aetherinvoice'
      path: '/aetherinvoice'
      fullPath: '/aetherinvoice'
      preLoaderRoute: typeof AetherinvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AetherinvoiceRoute: AetherinvoiceRoute,
  AethersignRoute: AethersignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
